package com.coronago.bq;

public enum BigQueryConfigOptions {
	USE_LEGACY_SQL,
	FLATTEN_RESULTS,
	REPLACE_DATA,
	PRINT_HEADER,
	PAGINATION,
	PAGINATION_RECORD_COUNT,
	TIME_PARTITIONING,
	EXPIRATION_IN_MS,
	EXPORT_DELIMITER,
	EMPTY_FILE_EXPORT,
	ALLOW_LARGE_RESULTS,
	CREATE_DISPOSITION,
	PARTITIONING_FIELD,
	DESTINATION_TABLE,
	DATASET
}
